name: august
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.6

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  avatar_glow: ^3.0.1
  change_app_package_name: ^1.3.0
  flutter:
    sdk: flutter
  hsv_color_pickers: ^0.3.0
  sign_in_with_apple: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  http: ^1.1.0
  image:
  json_annotation: ^4.0.1
  provider:
  sizer: ^2.0.15
  flutter_svg:
  colorful_safe_area:
  animations:
  skeleton_text: 
  shared_preferences:
  image_picker:
  path_provider:
  flutter_feather_icons: ^2.0.0
  modal_bottom_sheet: ^3.0.0-pre
  animated_text_kit:
  flutter_native_contact_picker: ^0.0.5
  contacts_service: ^0.6.1
  auth_buttons:
  google_sign_in: ^6.2.1
  shimmer:
  flutter_bouncing_widgets: ^1.0.3
  flutter_slidable: ^3.1.0
  image_cropper: ^7.0.5
  internet_connection_checker: ^1.0.0+1
  animated_hint_textfield: ^1.0.1
  intl: ^0.19.0
  sliding_number: ^0.0.4
  url_launcher: ^6.2.5
  toasty_box: 
  pull_to_refresh:
  flutter_native_splash:
  flutter_snake_navigationbar:
  syncfusion_flutter_charts: 
  lottie:
  custom_sliding_segmented_control:
  cached_network_image:
  google_mobile_ads: 
  flutter_dynamic_icon: ^2.1.0
flutter:
  fonts:
    - family: Nanum
      fonts:
        - asset: assets/fonts/NanumSquareRoundEB.ttf
          weight: 800  # Extra Bold
        - asset: assets/fonts/NanumSquareRoundB.ttf
          weight: 700  # Bold
        - asset: assets/fonts/NanumSquareRoundL.ttf
          weight: 300  # Light
        - asset: assets/fonts/NanumSquareRoundR.ttf
          weight: 400  # Regular

        

  assets:
  - assets/icons/horizontal-bar.svg
  - assets/icons/option.svg
  - assets/icons/semester.svg
  - assets/icons/grade.svg
  - assets/icons/major.svg
  - assets/icons/univ.svg
  - assets/icons/profile.svg
  - assets/icons/courses.png
  - assets/memoji/Memoji1.png
  - assets/memoji/Memoji2.png
  - assets/memoji/Memoji3.png
  - assets/memoji/Memoji4.png

  # season
  - assets/season/spring.svg
  - assets/season/summer.svg
  - assets/season/fall.svg
  - assets/season/winter.svg

  # splash
  - assets/icons/splash.png

  # launch icon
  - assets/launch/

  #lottie
  - assets/lottie/magic_wand.json
  - assets/lottie/share.json
  - assets/lottie/success.json
  uses-material-design: true
