// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjiL3Gebq_xwygzHXT0v6ZJpGh0gupfx8',
    appId: '1:615652326043:web:12e3633875a29ea140e43e',
    messagingSenderId: '615652326043',
    projectId: 'august-c7db0',
    authDomain: 'august-c7db0.firebaseapp.com',
    storageBucket: 'august-c7db0.appspot.com',
    measurementId: 'G-PKHK6K7YTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFK-Yhn9AOqyno4BvO5-RlzFaop3T_TS0',
    appId: '1:615652326043:android:2a205a051829738440e43e',
    messagingSenderId: '615652326043',
    projectId: 'august-c7db0',
    storageBucket: 'august-c7db0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjH5ReYPffv9K2XBptcN4uKeIw2DY7Asc',
    appId: '1:615652326043:ios:60a319188ab253e740e43e',
    messagingSenderId: '615652326043',
    projectId: 'august-c7db0',
    storageBucket: 'august-c7db0.appspot.com',
    iosBundleId: 'com.august',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjH5ReYPffv9K2XBptcN4uKeIw2DY7Asc',
    appId: '1:615652326043:ios:e0904015f59e4b5940e43e',
    messagingSenderId: '615652326043',
    projectId: 'august-c7db0',
    storageBucket: 'august-c7db0.appspot.com',
    iosBundleId: 'com.example.august',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjiL3Gebq_xwygzHXT0v6ZJpGh0gupfx8',
    appId: '1:615652326043:web:d6c34e488582aa0940e43e',
    messagingSenderId: '615652326043',
    projectId: 'august-c7db0',
    authDomain: 'august-c7db0.firebaseapp.com',
    storageBucket: 'august-c7db0.appspot.com',
    measurementId: 'G-P0GNF6P274',
  );
}
