name: august
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.5

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  avatar_glow: ^3.0.1
  cool_dropdown: ^2.1.0
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  hsv_color_pickers: ^0.3.0
  mirai_dropdown_menu: ^0.0.8+2
  flutter_popup:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  http: ^1.1.0
  image:
  json_annotation: ^4.0.1
  provider:
  sizer: ^2.0.15
  flutter_svg:
  colorful_safe_area:
  dynamic_timeline: ^0.1.2 
  dots_indicator:
  flutter_keyboard_visibility: 
  custom_navigation_bar:
  animations:
  skeleton_text: 
  card_swiper:
  shared_preferences:
  animated_digit:
  persistent_bottom_nav_bar:
  dropdown_search:
  google_nav_bar:
  qr_flutter:
  pull_down_button:
  image_picker:
  path_provider:
  flutter_feather_icons: ^2.0.0
  modal_bottom_sheet: ^3.0.0-pre
  animated_text_kit:
  permission_handler:
  flutter_native_contact_picker: ^0.0.5
  contacts_service: ^0.6.1
  auth_buttons:
  google_sign_in: ^6.2.1
  shimmer:
  flutter_animated_button: ^2.0.3
  flutter_animated_icons: ^1.0.1
  flutter_bouncing_widgets: ^1.0.3
  flutter_slidable: ^3.1.0
  gaimon: ^1.2.2+2
  image_cropper: ^7.0.5
  internet_connection_checker: ^1.0.0+1
  animated_hint_textfield: ^1.0.1
  intl: ^0.19.0
  page_view_dot_indicator: ^2.3.0
  sliding_number: ^0.0.4
  url_launcher: ^6.2.5
  toasty_box: 
  pull_to_refresh:
  flutter_native_splash:
  flutter_snake_navigationbar:
  syncfusion_flutter_charts: 
  sign_in_with_apple:
  lottie:

  
flutter:
  fonts:
    - family: Apple
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Light.ttf
        - asset: assets/fonts/SF-Pro-Rounded-Medium.ttf
          weight: 200
  assets:
  - assets/icons/horizontal-bar.svg
  - assets/icons/memoji.png
  - assets/icons/option.svg
  - assets/icons/semester.svg
  - assets/icons/grade.svg
  - assets/icons/major.svg
  - assets/icons/univ.svg
  - assets/icons/profile.svg
  - assets/memoji/Memoji1.png
  - assets/memoji/Memoji2.png
  - assets/memoji/Memoji3.png
  - assets/memoji/Memoji4.png
  - assets/test/umd.png

  # season
  - assets/season/spring.svg
  - assets/season/summer.svg
  - assets/season/fall.svg
  - assets/season/winter.svg

  #lottie
  - assets/lottie/magic_wand.json
  - assets/lottie/share.json
  uses-material-design: true
